baseurl = "http://alihafizji.com"
languageCode = "en-us"
title = "Ali's Website"
canonifyurls = true
disableKinds = ["taxonomy", "term"]

[params]
    [params.social]
        github      = "aliHafizji"
        facebook        = "ali.hafizji"
        facebook_admin  = "564590045"
        twitter     = "Ali_hafizji"
        twitter_domain  = "alihafizji.com"
        googleplus      = "alihafizji"
        instagram       = "olie_hafizji"
        linkedin        = "ali-hafizji"

    [params.authors]
        [params.authors.Ali]
          name          = "Ali Hafizji"
          thumbnail     = "http://www.raywenderlich.com/downloads/AliHafizji.jpg"
          images        = [
                            "https://pbs.twimg.com/profile_images/2449250013/c5nvv6x1dijvvbl4yxi4.jpeg"
                          ]
          bio           = "Writer. Freelance iOS, Android and Web Developer. Devoted husband. World's largest consumer of chocolate chip ice-cream."
          email         = "ali@alihafizji.com"

          [params.authors.Ali.social]
            github          = "aliHafizji"
            facebook        = "ali.hafizji"
            twitter         = "Ali_hafizji"
            googleplus      = "alihafizji"
            instagram       = "olie_hafizji"
            linkedin        = "ali-hafizji"
